### PR TITLE
Edit Personal details

### PR DESCRIPTION
**Pull request by KeharSr**

### CODE REVIEW

**Review by Pramesh167 — APPROVED** [review]

**Review by nwj002 — APPROVED** [review]
reviewed.

**Review by ShadipKumarJoshi — COMMENTED** [review]
reviewed

**Review by ShadipKumarJoshi — COMMENTED** [review]
reviewed

**Review by smritikhadgi98 — APPROVED** [review]

**Review by ShadipKumarJoshi — APPROVED** [review]
reviewed

**Pull request merged**
