### PR TITLE
UI changes done in login as admin screen

### PR DESCRIPTION
**Pull request by madhu502**

### CODE REVIEW

**Review by nwj002 — APPROVED** [review]
reviewed.

**Review by nwj002 — APPROVED** [review]
approved.

**Review by Pramesh167 — COMMENTED** [review]
verified

**Review by 220049 — COMMENTED** [review]
reviewed

**Review by Pramesh167 — APPROVED** [review]

**Review by Pramesh167 — APPROVED** [review]

**Review by smritikhadgi98 — APPROVED** [review]

**Review by KeharSr — APPROVED** [review]

**Pull request merged**
