### PR TITLE
onboarding screen

### PR DESCRIPTION
**Pull request by madhu502**

### CODE REVIEW

**Review by 220049 — APPROVED** [review]
h

**Review by 220049 — APPROVED** [review]
h

**Review by 220049 — APPROVED** [review]
h

**Review by 220049 — APPROVED** [review]
f

**Review by nwj002 — APPROVED** [review]
all looks good.

**Review by Pramesh167 — APPROVED** [review]

**Review by 220049 — APPROVED** [review]
ok

**Review by 220049 — APPROVED** [review]
ok

**Review by KeharSr — APPROVED** [review]

**Comment by nwj002** [comment]
solve all the conflicts.

**Pull request merged**
